import type { NormalizationConfig } from '@/types/scoring'

export const LAPTOP_CONFIG: NormalizationConfig = {
  price: {
    type: 'log_inverted',
    min: 20000,
    max: 300000,
    display_name: 'Price',
    description: 'Current market price',
    unit: '₹',
  },
  ram_gb: {
    type: 'log',
    min: 4,
    max: 64,
    higher_is_better: true,
    display_name: 'RAM',
    description: 'System memory',
    unit: 'GB',
  },
  storage_gb: {
    type: 'log',
    min: 128,
    max: 4096,
    higher_is_better: true,
    display_name: 'SSD Storage',
    description: 'Internal SSD storage',
    unit: 'GB',
  },
  battery_wh: {
    type: 'linear',
    min: 30,
    max: 100,
    higher_is_better: true,
    display_name: 'Battery Capacity',
    description: 'Battery capacity in watt-hours',
    unit: 'Wh',
  },
  display_inches: {
    type: 'tier',
    mapping: { '13': 0.6, '13.6': 0.7, '14': 0.85, '15': 0.9, '15.6': 1.0, '16': 0.95, '17': 0.8 },
    display_name: 'Screen Size',
    description: 'Display size',
    unit: 'inches',
  },
  display_hz: {
    type: 'tier',
    mapping: { '60': 0.3, '90': 0.6, '120': 0.85, '144': 1.0, '165': 1.0 },
    display_name: 'Display Refresh Rate',
    description: 'Screen refresh rate for smooth visuals',
    unit: 'Hz',
  },
  weight_kg: {
    type: 'inverted',
    min: 0.9,
    max: 3.5,
    display_name: 'Weight',
    description: 'Laptop weight for portability',
    unit: 'kg',
  },
  cpu_tier: {
    type: 'tier',
    mapping: {
      budget: 0.2,
      mid: 0.5,
      upper_mid: 0.7,
      high: 0.85,
      flagship: 1.0,
    },
    display_name: 'CPU Performance',
    description: 'Processor performance tier',
  },
  gpu_tier: {
    type: 'tier',
    mapping: { integrated: 0.2, entry_dedicated: 0.5, mid_dedicated: 0.7, high_dedicated: 1.0 },
    display_name: 'GPU',
    description: 'Graphics performance tier',
  },
  thunderbolt: {
    type: 'binary',
    display_name: 'Thunderbolt / USB4',
    description: 'High-speed Thunderbolt or USB4 port',
  },
  backlit_keyboard: {
    type: 'binary',
    display_name: 'Backlit Keyboard',
    description: 'Keyboard backlighting',
  },
}
