import type { NormalizationConfig } from '@/types/scoring'

export const SMARTPHONE_CONFIG: NormalizationConfig = {
  price: {
    type: 'log_inverted',
    min: 5000,
    max: 200000,
    display_name: 'Price',
    description: 'Current market price',
    unit: '₹',
  },
  ram_gb: {
    type: 'log',
    min: 2,
    max: 24,
    higher_is_better: true,
    display_name: 'RAM',
    description: 'System memory',
    unit: 'GB',
  },
  storage_gb: {
    type: 'log',
    min: 32,
    max: 1024,
    higher_is_better: true,
    display_name: 'Storage',
    description: 'Internal storage',
    unit: 'GB',
  },
  camera_mp: {
    type: 'log',
    min: 8,
    max: 200,
    higher_is_better: true,
    display_name: 'Main Camera',
    description: 'Main camera resolution',
    unit: 'MP',
  },
  battery_mah: {
    type: 'linear',
    min: 2000,
    max: 6000,
    higher_is_better: true,
    display_name: 'Battery',
    description: 'Battery capacity',
    unit: 'mAh',
  },
  charging_watts: {
    type: 'log',
    min: 10,
    max: 200,
    higher_is_better: true,
    display_name: 'Fast Charging',
    description: 'Maximum charging speed',
    unit: 'W',
  },
  display_hz: {
    type: 'tier',
    mapping: { '60': 0.3, '90': 0.6, '120': 0.85, '144': 1.0, '165': 1.0 },
    display_name: 'Display Refresh Rate',
    description: 'Screen refresh rate',
    unit: 'Hz',
  },
  display_inches: {
    type: 'linear',
    min: 5.5,
    max: 7.0,
    display_name: 'Screen Size',
    description: 'Display diagonal size',
    unit: 'inches',
  },
  has_nfc: {
    type: 'binary',
    display_name: 'NFC',
    description: 'Near Field Communication for payments',
  },
  has_5g: {
    type: 'binary',
    display_name: '5G',
    description: '5G network connectivity',
  },
  ip_rating: {
    type: 'tier',
    mapping: { none: 0, splash_resistant: 0.3, IP67: 0.7, IP68: 1.0 },
    display_name: 'Water Resistance',
    description: 'Dust and water protection rating',
  },
  weight_g: {
    type: 'inverted',
    min: 130,
    max: 230,
    display_name: 'Weight',
    description: 'Device weight',
    unit: 'g',
  },
}
